### PR TITLE
Issues/22 dihedral convention

### PR DESCRIPTION
**Pull request by davedavemckay**
Inversion of the sign of the dihedral angle arose from the direction of vector m.  This has been interted by changing m = cross(norm1, dr23) to m = cross(dr23, norm1).

A new test has been added (dihedral5, with associated .magres file) to confirm dihedral4 (-45 degrees) and dihedral5 (+45 degrees) have opposite sign.

### CODE REVIEW

**Comment by tfgg** [comment]
Why was this closed? It seems fine to me!

**Comment by davedavemckay** [comment]
I was worried about 'Travis CI build failed' - I thought maybe I put up the wrong version.

I've made a new request that's also fine and it says the same thing.

**Comment by davedavemckay** [comment]
sorry, messy I know

**Comment by tfgg** [comment]
I'm currently fixing the Travis CI thing, that's unrelated and not your fault :)

Ok, I'll merge the other one when I'm ready. If you want to modify a PR, you can easily push to the same branch and it'll update the PR - no need to make a new one.

**Comment by davedavemckay** [comment]
OK, good to know, thanks - I'll read the guides you put me on to before making any other changes so I know I'm doing things right.

**Pull request closed without merging**
